forcedotcom/SalesforceMobileSDK-CordovaPlugin

plugin.xml, src/ios/headers/SFAuthenticationManager.h, src/ios/headers/SFIdentityCoordinator.h, src/ios/headers/SFIdentityData.h, src/ios/headers/SFOAuthCoordinator.h, src/ios/headers/SFOAuthInfo.h, src/ios/resources/Images.xcassets/AppIcon.appiconset/Contents.json, tools/update.sh
Updating tools script, adding latest headers and whatnot from running `update.sh`.
=> Adding SalesforceSDKCommon, misc updates from repo

plugin.xml, tools/update.sh
=> Scripts update for openssl dependency removal

plugin.xml, tools/postinstall-android.js
Outstanding Items:
* Tweaking of ```settings.gradle``` (running into issues with inability to use newline character on BSD version of ```sed```).
* Tweaking of generated app's ```build.gradle``` (just because it's a pain in the ass and needs some thought to get foolproof logic around the patterns we search for).
* Copying ```Gradle``` wrapper files over (needs a bit of thought because we don't bundle it in the plugin repo right now).
=> More updates to make generated app work with Android Studio

tools/update.ps1
Less script update maintenance effort, since there's only one source of truth per platform.
=> Updating Win update script to not include Android and shared

plugin.xml, tools/update.ps1
Need to provide sqlite3.dll for Windows.
=> Changes for adding sqlite3.dll

src/windows/salesforce.windows.core.js, src/windows/src/CordovaPluginJavascript/salesforce.windows.core.js
Somehow I missed these files. We should have everything now
=> Add missing source files

tools/postinstall-android.js
the postinstall script didn't have a check to determine if the modifications it makes to the build.gradle file had already been made. Removing and re-installing the plugin caused problems for that reason.
=> Fix for build.gradle modifications

tools/postinstall-android.js
Noticed I had missed out a bracket on my last pull request.
=> Added missing bracket

tools/update.sh
Right now: building the ios repo by running ant fails. However the exit value was not being checked by update.sh so it just kept going and as a result, test_force.js would think that everything went well when it didn't.
=> Stopping at first error

tools/postinstall-android.js
=> Post install fails with shelljs 0.6.0

tools/update.sh
Reverts forcedotcom/SalesforceMobileSDK-CordovaPlugin#182
=> Revert "Change to update.sh script to not bring in sqlcipher bins anymore"

README.md
Add Version numbers for adding platforms as specified in the monile_sdk.pdf on page 135.
=> Update Readme to show correct platform version #'s

plugin.xml, src/android/libs/SalesforceSDK/src/com/salesforce/androidsdk/analytics/EventBuilderHelper.java, src/android/libs/SalesforceSDK/src/com/salesforce/androidsdk/util/JSONObjectHelper.java, src/android/libs/SalesforceSDK/src/com/salesforce/androidsdk/util/test/JSONTestHelper.java, src/android/libs/SmartStore/src/com/salesforce/androidsdk/smartstore/store/SmartStore.java, tools/after-platform-add-android.js
@wmathurin `edit-config` might need a newer version of `Cordova Android` platform, based on my preliminary research. This is low hanging fruit though and easier to manage.
=> Removing post install step for SDK versions

plugin.xml, src/ios/headers/SFSDKFileLogger.h, src/ios/headers/SalesforceSDKConstants.h, tools/update.sh
We've added some header includes in other public headers that require us to include these now.
=> Adding missing headers from the plugin

plugin.xml, src/ios/headers/DDFileLogger.h, src/ios/headers/DDLegacyMacros.h, src/ios/headers/DDLog.h, src/ios/headers/SFSDKFileLogger.h, src/ios/headers/SFSDKLogger.h, tools/update.sh
`SFSDKLogger.h` imports these 2 headers, so we need them as well.
=> Adding missing Lumberjack headers

plugin.xml
Min version should be 19 (for 5.3)
=> Code for 5.3 (part 2)

plugin.xml, tools/postinstall-android.js
Generated a `hybrid_local` and a `hybrid_remote` app using `forcehybrid` and verified they both work fine with `6.4.0`.
=> Upgrading to Cordova 6.4.0

tools/update.sh
iOS hybrid code now lives in SalesforceMobileSDK-iOS-Hybrid
=> Pointing plugin to ios hybrid repo

plugin.xml, tools/update.sh
Updates to work with latest SalesforceMobileSDK-iOS-Hybrid: logger without CocoaLumberJack
=> Updates to work with latest SalesforceMobileSDK-iOS-Hybrid

plugin.xml, tools/postinstall-android.js
Testing generated apps in progress.
=> Fixing scripts to work with the latest Android Studio and Cordova

plugin.xml
=> Fixing tagged version of podspecs

plugin.xml, setversion.sh
Also fixing setversion.sh to leave it alone
=> Fixing ios min version in plugin.xml

src/android/libs/MobileSync/src/com/salesforce/androidsdk/mobilesync/model/Layout.java, src/android/libs/MobileSync/src/com/salesforce/androidsdk/mobilesync/target/BatchSyncUpTarget.java, src/android/libs/SalesforceAnalytics/src/com/salesforce/androidsdk/analytics/store/EventStoreManager.java, src/android/libs/SalesforceHybrid/src/com/salesforce/androidsdk/phonegap/plugin/SalesforceNetworkPlugin.java, src/android/libs/SalesforceSDK/AndroidManifest.xml, src/android/libs/SalesforceSDK/src/com/salesforce/androidsdk/analytics/SalesforceAnalyticsManager.java, src/android/libs/SalesforceSDK/src/com/salesforce/androidsdk/app/SalesforceSDKManager.java, src/android/libs/SalesforceSDK/src/com/salesforce/androidsdk/rest/RestResponse.java, src/android/libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/OAuthWebviewHelper.java, src/ios/resources/SalesforceSDKResources.bundle/en.lproj/Localizable.strings
Ran `./tools/update.sh -b dev`
=> Latest from sources

gradle/wrapper/gradle-wrapper.properties, plugin.xml, src/android/libs/SalesforceAnalytics/src/com/salesforce/androidsdk/analytics/security/Encryptor.java, src/android/libs/SalesforceHybrid/res/xml/config.xml, src/android/libs/SalesforceSDK/src/com/salesforce/androidsdk/analytics/SalesforceAnalyticsManager.java, src/android/libs/SalesforceSDK/src/com/salesforce/androidsdk/auth/OAuth2.java, src/android/libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/OAuthWebviewHelper.java, src/android/libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/PasscodeActivity.java, src/android/libs/SmartStore/src/com/salesforce/androidsdk/smartstore/store/DBOpenHelper.java, src/android/libs/SmartStore/src/com/salesforce/androidsdk/smartstore/store/KeyValueEncryptedFileStore.java, src/ios/resources/Images.xcassets/AppIcon.appiconset/Contents.json
Also changed deployment target to 13.0 for iOS 
Also got latest sources
=> Upgrading cordova cli and cordova android

.gitignore, src/android/libs/SalesforceSDK/res/layout/sf__server_picker.xml, src/android/libs/SalesforceSDK/res/values/sf__colors.xml, src/android/libs/SalesforceSDK/res/values/sf__strings.xml, src/android/libs/SalesforceSDK/res/values/sf__styles.xml, src/android/libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/ServerPickerActivity.java
Also adding SalesforceMobileSDK-iOS to .gitignore
=> Latest sources

plugin.xml, src/android/libs/SalesforceAnalytics/src/com/salesforce/androidsdk/analytics/security/Encryptor.java, src/android/libs/SalesforceSDK/build.gradle, src/android/libs/SalesforceSDK/src/com/salesforce/androidsdk/accounts/UserAccountManager.java
The issue is that cordova-ios 6.2.0 has not been published to cocoapod.org. So we have to pull the dependency from git.
I filed an [issue on apache/cordova-ios](https://github.com/apache/cordova-ios/issues/1152) but there is no telling when it will get fixed.
=> Work around to get generated ios hybrid apps to work

plugin.xml, tools/postinstall-android.js
I figured out the right preference names by looking at https://github.com/apache/cordova-android/blob/10.1.1/lib/prepare.js#L91
=> Pinning down gradle and gradle plugin version

plugin.xml, src/android/libs/SalesforceHybrid/build.gradle, src/android/libs/SalesforceHybrid/res/values/themes.xml, src/android/libs/SalesforceSDK/src/com/salesforce/androidsdk/app/SalesforceSDKManager.java
=> Moving to cordova android 11.0.0

plugin.xml, src/android/libs/mobile_sdk/gradle.properties, src/android/libs/mobile_sdk/libs/SalesforceAnalytics/src/com/salesforce/androidsdk/analytics/security/Encryptor.java, src/android/libs/mobile_sdk/libs/SalesforceSDK/res/values/strings.xml, src/android/libs/mobile_sdk/libs/SalesforceSDK/src/com/salesforce/androidsdk/accounts/UserAccount.java, src/android/libs/mobile_sdk/libs/SalesforceSDK/src/com/salesforce/androidsdk/accounts/UserAccountManager.java, src/android/libs/mobile_sdk/libs/SalesforceSDK/src/com/salesforce/androidsdk/app/SalesforceSDKManager.kt, src/android/libs/mobile_sdk/libs/SalesforceSDK/src/com/salesforce/androidsdk/app/SalesforceSDKUpgradeManager.java, src/android/libs/mobile_sdk/libs/SalesforceSDK/src/com/salesforce/androidsdk/auth/NativeLoginManager.kt, src/android/libs/mobile_sdk/libs/SalesforceSDK/src/com/salesforce/androidsdk/auth/OAuth2.java, src/android/libs/mobile_sdk/libs/SalesforceSDK/src/com/salesforce/androidsdk/auth/interfaces/NativeLoginManager.kt, src/android/libs/mobile_sdk/libs/SalesforceSDK/src/com/salesforce/androidsdk/config/LoginServerManager.java, src/android/libs/mobile_sdk/libs/SalesforceSDK/src/com/salesforce/androidsdk/push/PushNotificationDecryptor.java, src/android/libs/mobile_sdk/libs/SalesforceSDK/src/com/salesforce/androidsdk/push/PushService.kt, src/android/libs/mobile_sdk/libs/SalesforceSDK/src/com/salesforce/androidsdk/rest/ApiVersionStrings.java, src/android/libs/mobile_sdk/libs/SalesforceSDK/src/com/salesforce/androidsdk/security/BiometricAuthenticationManager.kt, src/android/libs/mobile_sdk/libs/SalesforceSDK/src/com/salesforce/androidsdk/security/SalesforceKeyGenerator.java, src/android/libs/mobile_sdk/libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/OAuthWebviewHelper.kt, src/android/libs/mobile_sdk/libs/test/SalesforceSDKTest/src/com/salesforce/androidsdk/app/SalesforceSDKUpgradeManagerTest.kt, src/android/libs/mobile_sdk/libs/test/SalesforceSDKTest/src/com/salesforce/androidsdk/security/KeyStoreWrapperTest.java
=> Moving to cordova io 7.1.0

plugin.xml
🎸 _*Ready For Review!*_ 🥁
This updates to the latest Gradle and Android Gradle Plugin.  Note there is a Codova upgrade coming in this sprint also.
=> @W-18648586: Gradle upgrade
